"""Stable machine-readable identifiers for reviewer guard failures."""

from dataclasses import dataclass
from enum import StrEnum


class GuardCode(StrEnum):
    RC_REQUIREMENT_COVERAGE = "RC-REQUIREMENT-COVERAGE"
    RC_DUPLICATE_REQUIREMENT = "RC-DUPLICATE-REQUIREMENT"
    RC_UNEXPECTED_REQUIREMENT = "RC-UNEXPECTED-REQUIREMENT"
    RC_UNSATISFIED_REQUIREMENT = "RC-UNSATISFIED-REQUIREMENT"

    SP_DUPLICATE_EVIDENCE_CLUSTER = "SP-DUPLICATE-EVIDENCE-CLUSTER"
    SP_CLUSTER_HASH_MISMATCH = "SP-CLUSTER-HASH-MISMATCH"
    SP_REQUIRED_STAGE_INCOMPLETE = "SP-REQUIRED-STAGE-INCOMPLETE"
    SP_INAPPLICABLE_STAGE_NOT_SKIPPED = "SP-INAPPLICABLE-STAGE-NOT-SKIPPED"
    SP_STAGE_APPLICABILITY_MISMATCH = "SP-STAGE-APPLICABILITY-MISMATCH"
    SP_INVALID_FINDING_PROVENANCE = "SP-INVALID-FINDING-PROVENANCE"
    SP_CURRENT_BLOCKING_FINDING = "SP-CURRENT-BLOCKING-FINDING"
    SP_DUPLICATE_FINDING = "SP-DUPLICATE-FINDING"
    SP_UNKNOWN_ASSOCIATED_FINDING = "SP-UNKNOWN-ASSOCIATED-FINDING"
    SP_DUPLICATE_ASSOCIATION = "SP-DUPLICATE-ASSOCIATION"
    SP_MISSING_ASSOCIATION = "SP-MISSING-ASSOCIATION"

    IA_WRONG_REQUIREMENT_REFERENCE = "IA-WRONG-REQUIREMENT-REFERENCE"
    IA_INVALID_READ_REFERENCE = "IA-INVALID-READ-REFERENCE"
    IA_UNTRUSTED_DIFF_PATH = "IA-UNTRUSTED-DIFF-PATH"
    IA_MISSING_EXECUTION_SOURCE = "IA-MISSING-EXECUTION-SOURCE"
    IA_UNKNOWN_EXECUTION_SOURCE = "IA-UNKNOWN-EXECUTION-SOURCE"
    IA_INVALID_OBSERVATION_REFERENCE = "IA-INVALID-OBSERVATION-REFERENCE"
    IA_WRONG_OBSERVATION_REQUIREMENT = "IA-WRONG-OBSERVATION-REQUIREMENT"
    IA_OBSERVATION_PATH_MISMATCH = "IA-OBSERVATION-PATH-MISMATCH"
    IA_INVALID_EVIDENCE_RANGE = "IA-INVALID-EVIDENCE-RANGE"
    IA_UNGROUNDED_OBSERVATION = "IA-UNGROUNDED-OBSERVATION"
    IA_MISSING_DIRECT_CODE_OBSERVATION = "IA-MISSING-DIRECT-CODE-OBSERVATION"
    IA_MISSING_ASSERTION_OR_SIGNAL = "IA-MISSING-ASSERTION-OR-SIGNAL"
    IA_MISSING_DIRECT_EXECUTION_EVIDENCE = "IA-MISSING-DIRECT-EXECUTION-EVIDENCE"
    IA_MISSING_STRUCTURAL_EVIDENCE = "IA-MISSING-STRUCTURAL-EVIDENCE"

    II_UNKNOWN_OBSERVATION_REQUIREMENT = "II-UNKNOWN-OBSERVATION-REQUIREMENT"
    II_UNKNOWN_INSPECTION_REQUIREMENT = "II-UNKNOWN-INSPECTION-REQUIREMENT"

    FA_DUPLICATE_IDENTITY = "FA-DUPLICATE-IDENTITY"
    FA_INSPECTION_COVERAGE = "FA-INSPECTION-COVERAGE"
    FA_CHALLENGE_COVERAGE = "FA-CHALLENGE-COVERAGE"
    FA_UNKNOWN_OBSERVATION_REQUIREMENT = "FA-UNKNOWN-OBSERVATION-REQUIREMENT"
    FA_UNKNOWN_INSPECTION_REQUIREMENT = "FA-UNKNOWN-INSPECTION-REQUIREMENT"
    FA_MISSING_INSPECTION = "FA-MISSING-INSPECTION"
    FA_INSPECTION_NOT_VERIFIED = "FA-INSPECTION-NOT-VERIFIED"
    FA_MISSING_EVIDENCE = "FA-MISSING-EVIDENCE"
    FA_MISSING_CHALLENGE = "FA-MISSING-CHALLENGE"
    FA_CHALLENGE_NOT_SUPPORTED = "FA-CHALLENGE-NOT-SUPPORTED"


@dataclass(frozen=True)
class GuardProblem:
    """A stable guard identifier plus the unchanged, variable diagnostic text."""

    code: GuardCode
    detail: str

    def __str__(self) -> str:
        return self.detail
